# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Corne 3x6x3'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["crkbd"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
      clipboard: '["mac"]'
